version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data:/var/lib/postgresql/data

  odoo:
    image: odoo-debug
    depends_on:
      - db
    ports:
      - "8014:8069"
      - "5678:5678"  # Port for debugging
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    volumes:
      - ${ODOO_CONF_PATH}:/etc/odoo/odoo.conf  # Mount the local odoo.conf file
      - ${EXTRA_ADDONS_PATH}:/mnt/extra-addons  # Mount your custom addons
      - ${ODOO_SOURCE_PATH}:/usr/lib/python3/dist-packages/odoo  # Mount Odoo source code
      - ${FILESTORE_PATH}:/var/lib/odoo # Filestore
    command: >
      bash -c "python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client /usr/lib/python3/dist-packages/odoo/odoo-bin -c /etc/odoo/odoo.conf --dev xml"
